import type { TranslatorExportPacket } from './types'

const lines = (...items: string[]) => items.join('\n')

export const draftTemplates: Record<string, (packet: TranslatorExportPacket) => string> = {
  translator: packet =>
    lines(
      `// ${packet.page.title}`,
      'import SwiftUI',
      '',
      'struct TranslatorSpecDraftView: View {',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 18) {',
      '            Text("Translator Packet Draft")',
      '                .font(.headline)',
      '            Text("Prompt Ready")',
      '                .foregroundStyle(.secondary)',
      '            List {',
      '                Section("Components") {',
      ...packet.components.map(item => `                    Text("${item}")`),
      '                }',
      '            }',
      '        }',
      '        .padding(16)',
      '    }',
      '}',
    ),
  qq: () =>
    lines(
      '// QQ Chat',
      'import SwiftUI',
      '',
      'struct QQChatDraftView: View {',
      '    @State private var selectedTab = 0',
      '    @State private var draft = ""',
      '',
      '    var body: some View {',
      '        HStack(spacing: 0) {',
      '            VStack(spacing: 0) {',
      '                Picker("Tab", selection: $selectedTab) {',
      '                    Text("联系人").tag(0)',
      '                    Text("图片").tag(1)',
      '                    Text("文件").tag(2)',
      '                    Text("我").tag(3)',
      '                }',
      '                .pickerStyle(.segmented)',
      '            }',
      '            Divider()',
      '            VStack {',
      '                ScrollView {',
      '                    Text("Chat messages")',
      '                }',
      '                Divider()',
      '                TextEditor(text: $draft)',
      '                    .frame(minHeight: 120)',
      '            }',
      '        }',
      '    }',
      '}',
    ),
  'system-api': () =>
    lines(
      '// System API Mock',
      'import SwiftUI',
      '',
      'struct SystemApiMockDraftView: View {',
      '    @State private var fileName = "draft.txt"',
      '',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 18) {',
      '            TextField("file name", text: $fileName)',
      '            HStack {',
      '                Button("Create") {}',
      '                Button("Open URL") {}',
      '                Button("Reveal Downloads") {}',
      '            }',
      '            List {',
      '                Text("Recent events")',
      '            }',
      '        }',
      '        .padding(16)',
      '    }',
      '}',
    ),
  'component-document-group': () =>
    lines(
      '// DocumentGroup',
      'import SwiftUI',
      '',
      'struct DocumentGroupDraftView: View {',
      '    @State private var selection: String? = nil',
      '    @State private var nextName = "mock-note.txt"',
      '',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 18) {',
      '            Text("DocumentGroup")',
      '                .font(.headline)',
      '            TextField("rename file", text: $nextName)',
      '            HStack {',
      '                Button("Rename") {}',
      '                Button("Save") {}',
      '                Button("New") {}',
      '            }',
      '        }',
      '        .padding(16)',
      '    }',
      '}',
    ),
  'component-window-group': () =>
    lines(
      '// WindowGroup',
      'import SwiftUI',
      '',
      'struct WindowGroupDraftView: View {',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 16) {',
      '            Text("Preview Window")',
      '                .font(.headline)',
      '            Button("Open Utility") {}',
      '        }',
      '        .padding(16)',
      '        .frame(minWidth: 520, minHeight: 320)',
      '    }',
      '}',
    ),
  'component-commands': () =>
    lines(
      '// Commands',
      'import SwiftUI',
      '',
      'struct CommandsDraftView: Commands {',
      '    var body: some Commands {',
      '        CommandMenu("File") {',
      '            Button("New Window") {}',
      '            Button("Close") {}',
      '        }',
      '        CommandMenu("Edit") {',
      '            Button("Undo") {}',
      '            Button("Redo") {}',
      '        }',
      '    }',
      '}',
    ),
  'component-scene': () =>
    lines(
      '// Scene',
      'import SwiftUI',
      '',
      'struct SettingsSceneDraft: Scene {',
      '    var body: some Scene {',
      '        Settings {',
      '            Text("Scene acts as lifecycle/root grouping shell.")',
      '        }',
      '    }',
      '}',
    ),
  'component-runtime-state': () =>
    lines(
      '// Runtime State',
      'import SwiftUI',
      '',
      'final class RuntimeModel: ObservableObject {',
      '    @Published var count = 0',
      '}',
      '',
      'struct RuntimeStateDraftView: View {',
      '    @StateObject private var model = RuntimeModel()',
      '',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 12) {',
      '            Text("StateObject")',
      '            Button("Step") { model.count += 1 }',
      '        }',
      '        .padding(16)',
      '    }',
      '}',
    ),
  'component-navigation-stack': () =>
    lines(
      '// NavigationStack',
      'import SwiftUI',
      '',
      'struct NavigationStackDraftView: View {',
      '    @State private var path = NavigationPath()',
      '',
      '    var body: some View {',
      '        NavigationStack(path: $path) {',
      '            List {',
      '                NavigationLink("Open first message", value: "message-a")',
      '                NavigationLink("Open second message", value: "message-b")',
      '            }',
      '            .navigationDestination(for: String.self) { value in',
      '                Text(value)',
      '            }',
      '        }',
      '    }',
      '}',
    ),
  'component-list': () =>
    lines(
      '// List',
      'import SwiftUI',
      '',
      'struct ListDraftView: View {',
      '    @State private var selection: String? = "mac"',
      '',
      '    var body: some View {',
      '        List(selection: $selection) {',
      '            Section("Devices") {',
      '                NavigationLink("MacBook Pro", value: "mac")',
      '                NavigationLink("iPhone 16 Pro", value: "phone")',
      '            }',
      '        }',
      '    }',
      '}',
    ),
  'component-sheet': () =>
    lines(
      '// Sheet',
      'import SwiftUI',
      '',
      'struct SheetDraftView: View {',
      '    @State private var isPresented = false',
      '',
      '    var body: some View {',
      '        Button("打开 Sheet") { isPresented = true }',
      '            .sheet(isPresented: $isPresented) {',
      '                Text("Sheet 内容")',
      '                    .presentationDetents([.large])',
      '            }',
      '    }',
      '}',
    ),
  'component-popover': () =>
    lines(
      '// Popover',
      'import SwiftUI',
      '',
      'struct PopoverDraftView: View {',
      '    @State private var shown = false',
      '',
      '    var body: some View {',
      '        Button("Peer Info") { shown.toggle() }',
      '            .popover(isPresented: $shown, attachmentAnchor: .rect(.bounds), arrowEdge: .trailing) {',
      '                Text("LAN peer: freewind-mac")',
      '            }',
      '    }',
      '}',
    ),
  'component-table': () =>
    lines(
      '// Table',
      'import SwiftUI',
      '',
      'struct TableDraftView: View {',
      '    @State private var selection: String? = "p1"',
      '',
      '    var body: some View {',
      '        Table(of: String.self, selection: $selection) {',
      '            TableColumn("Device") { Text($0) }',
      '        } rows: {',
      '            TableRow("freewind-mac")',
      '            TableRow("freewind-ios")',
      '        }',
      '    }',
      '}',
    ),
  'component-text-field': () =>
    lines(
      '// TextField',
      'import SwiftUI',
      '',
      'struct TextFieldDraftView: View {',
      '    @State private var deviceName = "freewind-mac"',
      '    @FocusState private var focusedField: String?',
      '',
      '    var body: some View {',
      '        TextField("input device name", text: $deviceName)',
      '            .focused($focusedField, equals: "deviceName")',
      '            .submitLabel(.search)',
      '    }',
      '}',
    ),
  'component-text-editor': () =>
    lines(
      '// TextEditor',
      'import SwiftUI',
      '',
      'struct TextEditorDraftView: View {',
      '    @State private var draft = ""',
      '',
      '    var body: some View {',
      '        TextEditor(text: $draft)',
      '            .frame(minHeight: 140)',
      '            .padding(12)',
      '    }',
      '}',
    ),
  'native-swift-root-view': () =>
    lines(
      '// RootView',
      'import SwiftUI',
      '',
      'struct RootViewDraft: View {',
      '    var body: some View {',
      '        HStack(spacing: 0) {',
      '            Text("Contacts Pane")',
      '            Divider()',
      '            Text("Chat Pane")',
      '        }',
      '    }',
      '}',
    ),
  'native-swift-chat-screen': () =>
    lines(
      '// ChatScreen',
      'import SwiftUI',
      '',
      'struct ChatScreenDraft: View {',
      '    @State private var draft = ""',
      '',
      '    var body: some View {',
      '        VStack(spacing: 0) {',
      '            ScrollView {',
      '                Text("Messages")',
      '            }',
      '            Divider()',
      '            TextEditor(text: $draft)',
      '                .frame(minHeight: 120)',
      '        }',
      '    }',
      '}',
    ),
  'native-swift-composer-text-view': () =>
    lines(
      '// ComposerTextView',
      'import SwiftUI',
      '',
      'struct ComposerTextViewDraft: View {',
      '    @State private var draft = ""',
      '',
      '    var body: some View {',
      '        VStack(spacing: 8) {',
      '            TextEditor(text: $draft)',
      '            Button("Send") {}',
      '        }',
      '        .padding(12)',
      '    }',
      '}',
    ),
}
