import type { TranslatorExportPacket } from './types'

const lines = (...items: string[]) => items.join('\n')

export const draftTemplates: Record<string, (packet: TranslatorExportPacket) => string> = {
  translator: packet =>
    lines(
      `// ${packet.page.title}`,
      'import SwiftUI',
      '',
      'struct TranslatorSpecDraftView: View {',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 18) {',
      '            Text("Translator Packet Draft")',
      '                .font(.headline)',
      '            Text("Prompt Ready")',
      '                .foregroundStyle(.secondary)',
      '            List {',
      '                Section("Components") {',
      ...packet.components.map(item => `                    Text("${item}")`),
      '                }',
      '            }',
      '        }',
      '        .padding(16)',
      '    }',
      '}',
    ),
  qq: () =>
    lines(
      '// QQ Chat',
      'import SwiftUI',
      '',
      'struct QQChatDraftView: View {',
      '    @State private var selectedTab = 0',
      '    @State private var draft = ""',
      '',
      '    var body: some View {',
      '        HStack(spacing: 0) {',
      '            VStack(spacing: 0) {',
      '                Picker("Tab", selection: $selectedTab) {',
      '                    Text("联系人").tag(0)',
      '                    Text("图片").tag(1)',
      '                    Text("文件").tag(2)',
      '                    Text("我").tag(3)',
      '                }',
      '                .pickerStyle(.segmented)',
      '            }',
      '            Divider()',
      '            VStack {',
      '                ScrollView {',
      '                    Text("Chat messages")',
      '                }',
      '                Divider()',
      '                TextEditor(text: $draft)',
      '                    .frame(minHeight: 120)',
      '            }',
      '        }',
      '    }',
      '}',
    ),
  'system-api': () =>
    lines(
      '// System API Mock',
      'import SwiftUI',
      '',
      'struct SystemApiMockDraftView: View {',
      '    @State private var fileName = "draft.txt"',
      '',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 18) {',
      '            TextField("file name", text: $fileName)',
      '            HStack {',
      '                Button("Create") {}',
      '                Button("Open URL") {}',
      '                Button("Reveal Downloads") {}',
      '            }',
      '            List {',
      '                Text("Recent events")',
      '            }',
      '        }',
      '        .padding(16)',
      '    }',
      '}',
    ),
  'component-document-group': () =>
    lines(
      '// DocumentGroup',
      'import SwiftUI',
      '',
      'struct DocumentGroupDraftView: View {',
      '    @State private var selection: String? = nil',
      '    @State private var nextName = "mock-note.txt"',
      '',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 18) {',
      '            Text("DocumentGroup")',
      '                .font(.headline)',
      '            TextField("rename file", text: $nextName)',
      '            HStack {',
      '                Button("Rename") {}',
      '                Button("Save") {}',
      '                Button("New") {}',
      '            }',
      '        }',
      '        .padding(16)',
      '    }',
      '}',
    ),
  'component-window-group': () =>
    lines(
      '// WindowGroup',
      'import SwiftUI',
      '',
      'struct WindowGroupDraftView: View {',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 16) {',
      '            Text("Preview Window")',
      '                .font(.headline)',
      '            Button("Open Utility") {}',
      '        }',
      '        .padding(16)',
      '        .frame(minWidth: 520, minHeight: 320)',
      '    }',
      '}',
    ),
  'component-commands': () =>
    lines(
      '// Commands',
      'import SwiftUI',
      '',
      'struct CommandsDraftView: Commands {',
      '    var body: some Commands {',
      '        CommandMenu("File") {',
      '            Button("New Window") {}',
      '            Button("Close") {}',
      '        }',
      '        CommandMenu("Edit") {',
      '            Button("Undo") {}',
      '            Button("Redo") {}',
      '        }',
      '    }',
      '}',
    ),
  'component-scene': () =>
    lines(
      '// Scene',
      'import SwiftUI',
      '',
      'struct SettingsSceneDraft: Scene {',
      '    var body: some Scene {',
      '        Settings {',
      '            Text("Scene acts as lifecycle/root grouping shell.")',
      '        }',
      '    }',
      '}',
    ),
  'component-runtime-state': () =>
    lines(
      '// Runtime State',
      'import SwiftUI',
      '',
      'final class RuntimeModel: ObservableObject {',
      '    @Published var count = 0',
      '}',
      '',
      'struct RuntimeStateDraftView: View {',
      '    @StateObject private var model = RuntimeModel()',
      '',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 12) {',
      '            Text("StateObject")',
      '            Button("Step") { model.count += 1 }',
      '        }',
      '        .padding(16)',
      '    }',
      '}',
    ),
  'component-navigation-stack': () =>
    lines(
      '// NavigationStack',
      'import SwiftUI',
      '',
      'struct NavigationStackDraftView: View {',
      '    @State private var path = NavigationPath()',
      '',
      '    var body: some View {',
      '        NavigationStack(path: $path) {',
      '            List {',
      '                NavigationLink("Open first message", value: "message-a")',
      '                NavigationLink("Open second message", value: "message-b")',
      '            }',
      '            .navigationDestination(for: String.self) { value in',
      '                Text(value)',
      '            }',
      '        }',
      '    }',
      '}',
    ),
  'component-navigation-link': () =>
    lines(
      '// NavigationLink',
      'import SwiftUI',
      '',
      'struct NavigationLinkDraftView: View {',
      '    var body: some View {',
      '        List {',
      '            NavigationLink("General", value: "general")',
      '            NavigationLink(value: "device-detail") {',
      '                VStack(alignment: .leading, spacing: 2) {',
      '                    Text("Current Device")',
      '                    Text("open device detail")',
      '                        .font(.caption)',
      '                        .foregroundStyle(.secondary)',
      '                }',
      '            }',
      '        }',
      '        .navigationDestination(for: String.self) { value in',
      '            Text(value)',
      '        }',
      '    }',
      '}',
    ),
  'component-list': () =>
    lines(
      '// List',
      'import SwiftUI',
      '',
      'struct ListDraftView: View {',
      '    @State private var selection: String? = "mac"',
      '',
      '    var body: some View {',
      '        List(selection: $selection) {',
      '            Section("Devices") {',
      '                NavigationLink("MacBook Pro", value: "mac")',
      '                NavigationLink("iPhone 16 Pro", value: "phone")',
      '            }',
      '        }',
      '    }',
      '}',
    ),
  'component-tab-view': () =>
    lines(
      '// TabView',
      'import SwiftUI',
      '',
      'struct TabViewDraft: View {',
      '    @State private var selectedTab = "contacts"',
      '',
      '    var body: some View {',
      '        TabView(selection: $selectedTab) {',
      '            Text("联系人列表内容")',
      '                .tabItem { Label("联系人", systemImage: "iphone") }',
      '                .badge(3)',
      '                .tag("contacts")',
      '            Text("图片流内容")',
      '                .tabItem { Label("图片", systemImage: "photo") }',
      '                .tag("images")',
      '            Text("文件流内容")',
      '                .tabItem { Label("文件", systemImage: "doc") }',
      '                .tag("files")',
      '        }',
      '        .tint(.green)',
      '    }',
      '}',
    ),
  'component-sheet': () =>
    lines(
      '// Sheet',
      'import SwiftUI',
      '',
      'struct SheetDraftView: View {',
      '    @State private var isPresented = false',
      '',
      '    var body: some View {',
      '        Button("打开 Sheet") { isPresented = true }',
      '            .sheet(isPresented: $isPresented) {',
      '                Text("Sheet 内容")',
      '                    .presentationDetents([.large])',
      '            }',
      '    }',
      '}',
    ),
  'component-popover': () =>
    lines(
      '// Popover',
      'import SwiftUI',
      '',
      'struct PopoverDraftView: View {',
      '    @State private var shown = false',
      '',
      '    var body: some View {',
      '        Button("Peer Info") { shown.toggle() }',
      '            .popover(isPresented: $shown, attachmentAnchor: .rect(.bounds), arrowEdge: .trailing) {',
      '                Text("LAN peer: freewind-mac")',
      '            }',
      '    }',
      '}',
    ),
  'component-alert': () =>
    lines(
      '// Alert',
      'import SwiftUI',
      '',
      'struct AlertDraftView: View {',
      '    @State private var isPresented = false',
      '',
      '    var body: some View {',
      '        Button("show alert") { isPresented = true }',
      '            .alert("删除会话？", isPresented: $isPresented) {',
      '                Button("取消", role: .cancel) {}',
      '                Button("删除", role: .destructive) {}',
      '            } message: {',
      '                Text("此操作无法撤销。")',
      '            }',
      '    }',
      '}',
    ),
  'component-confirmation-dialog': () =>
    lines(
      '// ConfirmationDialog',
      'import SwiftUI',
      '',
      'struct ConfirmationDialogDraftView: View {',
      '    @State private var isPresented = false',
      '',
      '    var body: some View {',
      '        Button("show dialog") { isPresented = true }',
      '            .confirmationDialog("选择操作", isPresented: $isPresented, titleVisibility: .visible) {',
      '                Button("置顶") {}',
      '                Button("删除", role: .destructive) {}',
      '                Button("取消", role: .cancel) {}',
      '            } message: {',
      '                Text("这些操作会立即影响当前会话。")',
      '            }',
      '    }',
      '}',
    ),
  'component-table': () =>
    lines(
      '// Table',
      'import SwiftUI',
      '',
      'struct TableDraftView: View {',
      '    @State private var selection: String? = "p1"',
      '',
      '    var body: some View {',
      '        Table(of: String.self, selection: $selection) {',
      '            TableColumn("Device") { Text($0) }',
      '        } rows: {',
      '            TableRow("freewind-mac")',
      '            TableRow("freewind-ios")',
      '        }',
      '    }',
      '}',
    ),
  'component-picker': () =>
    lines(
      '// Picker',
      'import SwiftUI',
      '',
      'struct PickerDraftView: View {',
      '    @State private var selection = "all"',
      '',
      '    var body: some View {',
      '        Picker("peer filter", selection: $selection) {',
      '            Text("全部").tag("all")',
      '            Text("在线").tag("online")',
      '            Text("离线").tag("offline")',
      '        }',
      '        .pickerStyle(.segmented)',
      '        .labelsHidden()',
      '        .controlSize(.mini)',
      '        .tint(.green)',
      '    }',
      '}',
    ),
  'component-toggle': () =>
    lines(
      '// Toggle',
      'import SwiftUI',
      '',
      'struct ToggleDraftView: View {',
      '    @State private var wifi = true',
      '    @State private var notifications = false',
      '',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 12) {',
      '            Toggle("Wi-Fi", isOn: $wifi)',
      '                .tint(.green)',
      '            Toggle(isOn: $notifications) {',
      '                VStack(alignment: .leading, spacing: 2) {',
      '                    Text("通知提醒")',
      '                    Text("preview banners")',
      '                        .font(.caption)',
      '                        .foregroundStyle(.secondary)',
      '                }',
      '            }',
      '        }',
      '        .padding(16)',
      '    }',
      '}',
    ),
  'component-slider': () =>
    lines(
      '// Slider',
      'import SwiftUI',
      '',
      'struct SliderDraftView: View {',
      '    @State private var zoom = 80.0',
      '',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 10) {',
      '            Slider(value: $zoom, in: 10 ... 200, step: 5) {',
      '                Text("Zoom")',
      '            } minimumValueLabel: {',
      '                Text("10%")',
      '            } maximumValueLabel: {',
      '                Text("200%")',
      '            }',
      '            .tint(.green)',
      '            Text("zoom: \\(Int(zoom))%")',
      '                .font(.caption)',
      '                .foregroundStyle(.secondary)',
      '        }',
      '        .padding(16)',
      '    }',
      '}',
    ),
  'component-stepper': () =>
    lines(
      '// Stepper',
      'import SwiftUI',
      '',
      'struct StepperDraftView: View {',
      '    @State private var count = 2',
      '',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 10) {',
      '            Stepper(value: $count, in: 0 ... 10, step: 1) {',
      '                VStack(alignment: .leading, spacing: 2) {',
      '                    Text("Concurrent Uploads")',
      '                    Text("\\(count) jobs")',
      '                        .font(.caption)',
      '                        .foregroundStyle(.secondary)',
      '                }',
      '            }',
      '            .tint(.blue)',
      '            Stepper("Retry Count", value: $count, in: 1 ... 8, step: 1)',
      '                .controlSize(.mini)',
      '        }',
      '        .padding(16)',
      '    }',
      '}',
    ),
  'component-text-field': () =>
    lines(
      '// TextField',
      'import SwiftUI',
      '',
      'struct TextFieldDraftView: View {',
      '    @State private var deviceName = "freewind-mac"',
      '    @FocusState private var focusedField: String?',
      '',
      '    var body: some View {',
      '        TextField("input device name", text: $deviceName)',
      '            .focused($focusedField, equals: "deviceName")',
      '            .submitLabel(.search)',
      '    }',
      '}',
    ),
  'component-secure-field': () =>
    lines(
      '// SecureField',
      'import SwiftUI',
      '',
      'struct SecureFieldDraftView: View {',
      '    @State private var password = "hunter2"',
      '    @FocusState private var focusedField: String?',
      '',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 10) {',
      '            SecureField("password", text: $password)',
      '                .focused($focusedField, equals: "password")',
      '                .submitLabel(.done)',
      '            Text("长度：\\(password.count)")',
      '                .font(.caption)',
      '                .foregroundStyle(.secondary)',
      '        }',
      '        .padding(16)',
      '    }',
      '}',
    ),
  'component-text-editor': () =>
    lines(
      '// TextEditor',
      'import SwiftUI',
      '',
      'struct TextEditorDraftView: View {',
      '    @State private var draft = ""',
      '',
      '    var body: some View {',
      '        TextEditor(text: $draft)',
      '            .frame(minHeight: 140)',
      '            .padding(12)',
      '    }',
      '}',
    ),
  'component-window-accessor': () =>
    lines(
      '// WindowAccessor',
      'import SwiftUI',
      '',
      'struct WindowAccessorDraftView: View {',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 8) {',
      '            Text("当前版本仅保留窗口语义占位。")',
      '            Text("真实窗口句柄访问应下沉到 runtime / native bridge。")',
      '                .foregroundStyle(.secondary)',
      '        }',
      '        .padding(16)',
      '    }',
      '}',
    ),
  todo: () =>
    lines(
      '// Todo List',
      'import SwiftUI',
      '',
      'struct TodoDraftView: View {',
      '    @State private var segment = "all"',
      '    @State private var input = "给 SwiftUI JSX demo 再加更多 case"',
      '',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 14) {',
      '            Picker("Filter", selection: $segment) {',
      '                Text("全部").tag("all")',
      '                Text("待办").tag("open")',
      '                Text("完成").tag("done")',
      '            }',
      '            .pickerStyle(.segmented)',
      '            HStack {',
      '                TextField("new task", text: $input)',
      '                    .textFieldStyle(.roundedBorder)',
      '                Button("添加") {}',
      '            }',
      '        }',
      '        .padding(16)',
      '    }',
      '}',
    ),
  'image-browser': () =>
    lines(
      '// Image Browser',
      'import SwiftUI',
      '',
      'struct ImageBrowserDraftView: View {',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 14) {',
      '            HStack(spacing: 14) {',
      '                ImageTile(title: "LAN Peers", tone: .blue, size: "2400 x 1600")',
      '                ImageTile(title: "Transfers", tone: .green, size: "1800 x 1200")',
      '            }',
      '        }',
      '        .padding(16)',
      '    }',
      '}',
      '',
      'private struct ImageTile: View {',
      '    let title: String',
      '    let tone: Color',
      '    let size: String',
      '',
      '    var body: some View {',
      '        VStack(alignment: .leading, spacing: 10) {',
      '            RoundedRectangle(cornerRadius: 14)',
      '                .fill(tone)',
      '                .frame(height: 160)',
      '                .overlay { Text(title).font(.title2).foregroundStyle(.white) }',
      '            Text(title)',
      '                .font(.headline)',
      '            Text(size)',
      '                .font(.caption)',
      '                .foregroundStyle(.secondary)',
      '        }',
      '        .padding(12)',
      '        .background(.thinMaterial, in: RoundedRectangle(cornerRadius: 18))',
      '    }',
      '}',
    ),
  'file-browser': () =>
    lines(
      '// File Browser',
      'import SwiftUI',
      '',
      'struct FileBrowserDraftView: View {',
      '    var body: some View {',
      '        HStack(spacing: 0) {',
      '            VStack(alignment: .leading, spacing: 8) {',
      '                Text("Favorites").font(.headline)',
      '                Button("Documents") {}',
      '                Button("Downloads") {}',
      '                Button("Pictures") {}',
      '            }',
      '            .padding(14)',
      '            .frame(width: 220, alignment: .leading)',
      '            Divider()',
      '            VStack(alignment: .leading, spacing: 12) {',
      '                HStack {',
      '                    Text("Documents").font(.title3.weight(.semibold))',
      '                    Spacer()',
      '                    Button("New Folder") {}',
      '                }',
      '                ForEach(["Product Brief.md", "Release Assets", "Preview.png"], id: \\.self) { item in',
      '                    Label(item, systemImage: "doc")',
      '                        .frame(maxWidth: .infinity, alignment: .leading)',
      '                        .padding(12)',
      '                        .background(.thinMaterial, in: RoundedRectangle(cornerRadius: 14))',
      '                }',
      '            }',
      '            .padding(14)',
      '            .frame(maxWidth: .infinity, alignment: .leading)',
      '        }',
      '    }',
      '}',
    ),
}
