import rootViewSwiftSource from '/Users/peng.li/workspace/freewind-qq/native/macos/Sources/FreewindQQMac/Features/RootView.swift?raw'
import chatScreenSwiftSource from '/Users/peng.li/workspace/freewind-qq/native/macos/Sources/FreewindQQMac/Features/ChatScreen.swift?raw'
import composerTextViewSwiftSource from '/Users/peng.li/workspace/freewind-qq/native/macos/Sources/FreewindQQMac/ComposerTextView.swift?raw'
import type { TranslatorExportPacket } from './types'

export type TranslatorPageMeta = {
  id: string
  title: string
  intent: string
  category: 'translator' | 'native-swift' | 'app' | 'component'
  swiftSource?: string
}

export type TranslatorCoverage = {
  aligned: string[]
  stub: string[]
  gap: string[]
}

export type TranslatorPageSpec = Omit<TranslatorExportPacket, 'page'> & {
  page: TranslatorPageMeta
  coverage?: TranslatorCoverage
}

type TranslatorPageSpecInput = Omit<TranslatorPageSpec, 'constraints' | 'mappings'> &
  Partial<Pick<TranslatorExportPacket, 'constraints' | 'mappings'>>

const baseConstraints = [
  '业务层禁原生 DOM 标签，优先走 src/swift DSL 组件。',
  '真实 IO 不直连，文件/系统/打开 URL 优先走 mock facade。',
  '状态优先表达为 State/Binding/EnvironmentObject/FocusedValues。',
  '输出目标是 SwiftUI，可接受 stub，但参数/用法应尽量贴近 SwiftUI/OpenSwiftUI。',
]

const baseMappings = [
  { jsx: '<VStack spacing={12}>', swiftui: 'VStack(spacing: 12) { ... }' },
  { jsx: '<TextField text={name} />', swiftui: 'TextField("", text: $name)' },
  { jsx: '<DocumentGroup documents={docs} selection={selection} />', swiftui: 'DocumentGroup { ... }' },
  { jsx: '<NavigationLink value="detail" />', swiftui: 'NavigationLink(value: "detail") { ... }' },
]

const makeSpec = (spec: TranslatorPageSpecInput): TranslatorPageSpec => ({
  ...spec,
  constraints: spec.constraints ?? baseConstraints,
  mappings: spec.mappings ?? baseMappings,
})

const specs: TranslatorPageSpec[] = [
  makeSpec({
    page: { id: 'translator', title: '转换规约', intent: '给 AE/AI 一份稳定的 JSX -> SwiftUI 结构化输入包。', category: 'translator' },
    stateModels: ['Binding<T>', 'ObservableObject<T>', 'NavigationPath', 'FileDocument'],
    apiFacades: ['MockEnvironment', 'AppShell', 'AppSystemApi', 'AppFileApi'],
    components: ['Text', 'Button', 'VStack', 'HStack', 'DocumentGroup', 'NavigationStack', 'List', 'Table'],
    modifiers: ['padding', 'frame', 'background', 'foregroundStyle', 'tint', 'controlSize', 'lineLimit', 'labelsHidden'],
    fewShot: [
      'JSX: <Toggle isOn={wifi} title="Wi-Fi" /> -> SwiftUI: Toggle("Wi-Fi", isOn: $wifi)',
      'JSX: <Sheet isPresented={shown}>...</Sheet> -> SwiftUI: .sheet(isPresented: $shown) { ... }',
    ],
    prompt: '你是 SwiftUI 转换器。基于 packet 把 JSX DSL 转成 SwiftUI，优先保留状态 shape、容器结构、modifier 顺序、系统 facade 边界。',
    jsxSource: [
      '<VStack spacing={18}>',
      '  <DocumentGroup documents={documents} selection={selection}>',
      '    <NavigationStack path={path}>',
      '      <List selection={selectedRow}>...</List>',
      '    </NavigationStack>',
      '  </DocumentGroup>',
      '</VStack>',
    ].join('\n'),
    coverage: {
      aligned: ['TranslatorExportPacket', 'page-aware draft', '真实 Swift compare workspace'],
      stub: ['AST 自动抽取', '更细粒度 capability 推断'],
      gap: ['从 Swift 源反向生成 JSX'],
    },
  }),
  makeSpec({
    page: {
      id: 'native-swift-root-view',
      title: 'RootView',
      intent: '把真实 Swift RootView 对照为可转 SwiftUI 的 JSX/mock 壳。',
      category: 'native-swift',
      swiftSource: rootViewSwiftSource,
    },
    stateModels: ['Binding<Int>', 'NavigationPath', 'MockEnvironment', 'AppShell'],
    apiFacades: ['AppShell', 'AppSystemApi', 'AppFileApi'],
    components: ['NavigationStack', 'List', 'Picker', 'Text', 'Button', 'HStack', 'VStack'],
    modifiers: ['padding', 'frame', 'background', 'foregroundStyle', 'tint', 'controlSize'],
    fewShot: ['Swift RootView 联系人侧栏 -> JSX HStack + VStack + Picker + mock app shell', 'Swift NavigationSplit-ish layout -> JSX HStack + detail pane'],
    prompt: '把 RootView.swift 对照成 SwiftUI/JSX 双向稳定表示，保留侧栏、选择态、mock facade 边界，不要引入真实 IO。',
    jsxSource: ['<HStack spacing={0}>', '  <ContactsPaneMini />', '  <Divider axis="vertical" />', '  <ChatPanel draft={draft} />', '</HStack>'].join('\n'),
    coverage: { aligned: ['分栏壳', '联系人/聊天布局', 'mock app shell 边界'], stub: ['NavigationSplitView 细语义', 'toolbar/title bar'], gap: ['真实窗口 chrome'] },
  }),
  makeSpec({
    page: {
      id: 'native-swift-chat-screen',
      title: 'ChatScreen',
      intent: '把真实聊天页结构映射到 JSX DSL 与 SwiftUI draft。',
      category: 'native-swift',
      swiftSource: chatScreenSwiftSource,
    },
    stateModels: ['Binding<String>', 'ChatMessage[]', 'PeerDigest', 'FocusedValues'],
    apiFacades: ['AppShell', 'AppFileApi'],
    components: ['ScrollView', 'TextEditor', 'Button', 'Sheet', 'Popover', 'NavigationLink'],
    modifiers: ['padding', 'frame', 'background', 'lineLimit', 'labelsHidden'],
    fewShot: ['消息列表 -> ScrollView + VStack + message row', '附件弹层 -> Sheet/Popover + mock save/open facade'],
    prompt: '把 ChatScreen.swift 转成结构稳定的 SwiftUI/JSX，对消息列表、输入区、附件动作优先保留状态和 facade 边界。',
    jsxSource: ['<VStack spacing={0}>', '  <ScrollView>...</ScrollView>', '  <Divider />', '  <TextEditor text={draft} />', '</VStack>'].join('\n'),
    coverage: { aligned: ['消息列表结构', '输入区壳', '附件 facade'], stub: ['滚动定位', '输入法/键盘桥接'], gap: ['真实富文本/粘贴板桥接'] },
  }),
  makeSpec({
    page: {
      id: 'native-swift-composer-text-view',
      title: 'ComposerTextView',
      intent: '把真实输入框桥接层压缩为 DSL 可表达的输入语义。',
      category: 'native-swift',
      swiftSource: composerTextViewSwiftSource,
    },
    stateModels: ['Binding<String>', 'FocusedValues', 'FocusState<String | null>'],
    apiFacades: ['AppSystemApi'],
    components: ['TextEditor', 'TextField', 'Button', 'Popover'],
    modifiers: ['tint', 'controlSize', 'lineLimit'],
    fewShot: ['NSTextView bridge -> TextEditor + FocusState + submit/draft state', '快捷动作按钮 -> Button + Popover'],
    prompt: '把 ComposerTextView.swift 提炼成输入控件 DSL，优先保留 focus、draft、submit 与系统能力边界。',
    jsxSource: ['<VStack spacing={8}>', '  <TextEditor text={draft} focused={focus} equals="composer" />', '  <HStack><Button title="Send" /></HStack>', '</VStack>'].join('\n'),
    coverage: { aligned: ['draft/focus', '发送动作壳', '系统动作边界'], stub: ['多段文本属性', 'IME bridge'], gap: ['原生 NSTextView delegate 细节'] },
  }),
  makeSpec({
    page: { id: 'qq', title: 'QQ Chat', intent: '把聊天应用壳、联系人、消息列表、输入区转成 SwiftUI 稳定结构。', category: 'app' },
    stateModels: ['Binding<number>', 'Binding<string>', 'PeerDigest[]', 'ChatMessage[]'],
    apiFacades: ['AppShell', 'AppSystemApi', 'AppFileApi', 'MockEnvironment'],
    components: ['HStack', 'VStack', 'ScrollView', 'Picker', 'TextEditor', 'Sheet', 'Button', 'List'],
    modifiers: ['padding', 'frame', 'background', 'foregroundStyle', 'tint', 'controlSize', 'lineLimit'],
    fewShot: ['联系人列表 -> ScrollView + peer row', '输入区 -> TextEditor + toolbar style buttons'],
    prompt: '把 QQ demo 提炼成 SwiftUI 兼容壳，优先保留 app shell facade、消息状态、附件动作与分栏布局。',
    jsxSource: ['<HStack spacing={0}>', '  <ContactsPaneMini />', '  <Divider axis="vertical" />', '  <ChatPanel draft={draft} />', '</HStack>'].join('\n'),
    coverage: { aligned: ['app shell facade', '消息状态', '附件动作', '分栏布局'], stub: ['更细聊天动画', '发送失败/重试视觉'], gap: ['真实网络状态'] },
  }),
  makeSpec({
    page: { id: 'system-api', title: 'System API Mock', intent: '把 system/file/open-url/mock fs 操作导出给 AI 做 SwiftUI facade 映射。', category: 'app' },
    stateModels: ['MockEnvironment', 'MockFileNode[]', 'MockOpenEvent[]'],
    apiFacades: ['AppSystemApi', 'AppFileApi', 'MockEnvironment'],
    components: ['FormSection', 'Button', 'TextField', 'List', 'ScrollView', 'Text'],
    modifiers: ['padding', 'frame', 'background', 'foregroundStyle', 'labelsHidden'],
    fewShot: ['openUrl -> system facade event', 'fake fs create/delete/reveal -> in-memory file tree update'],
    prompt: '把 system api mock 页面转成 SwiftUI 管理台，保留 fake fs、recent events、open/reveal/url facade。',
    jsxSource: ['<VStack spacing={18}>', '  <Button title="Create File" />', '  <List>recent events...</List>', '</VStack>'].join('\n'),
    coverage: { aligned: ['openUrl', 'documentByPath', 'recent events', 'in-memory fs'], stub: ['更细 picker/pasteboard'], gap: ['真实文件系统'] },
  }),
  makeSpec({
    page: { id: 'component-runtime-state', title: 'Runtime State', intent: '展示 DynamicProperty 兼容面，供 SwiftUI 状态映射参考。', category: 'component' },
    stateModels: ['StateObject', 'ObservedObject', 'EnvironmentObject', 'FocusedValues'],
    apiFacades: ['SceneLifecycleProvider'],
    components: ['EnvironmentObjectProvider', 'FocusedValuesProvider', 'Button', 'Text', 'VStack'],
    modifiers: ['padding', 'background', 'frame', 'foregroundStyle'],
    fewShot: ['EnvironmentObject provider -> child read', 'FocusedValues -> focus driven derived label'],
    prompt: '把 runtime state demo 当成 SwiftUI 状态映射 reference，保留 provider 与 dynamic property 关系。',
    jsxSource: ['<EnvironmentObjectProvider>', '  <FocusedValuesProvider>...</FocusedValuesProvider>', '</EnvironmentObjectProvider>'].join('\n'),
    coverage: { aligned: ['EnvironmentObject', 'FocusedValues', 'OpenURLAction'], stub: ['ObservedObject 发布链', 'Storage 持久化'], gap: ['真实 scene/app storage'] },
  }),
  makeSpec({
    page: { id: 'component-document-group', title: 'DocumentGroup', intent: '展示 document open/save/new/select 生命周期与 mock fs 边界。', category: 'component' },
    stateModels: ['FileDocument[]', 'Binding<string | null>', 'MockDocumentWorkspace'],
    apiFacades: ['MockEnvironment', 'AppFileApi'],
    components: ['DocumentGroup', 'TextField', 'Button', 'Picker', 'ScrollView'],
    modifiers: ['padding', 'frame', 'background', 'controlSize'],
    fewShot: ['open/save/new/select document -> DocumentGroup + mock workspace', 'mock fs rename/delete -> environment facade'],
    prompt: '把 DocumentGroup demo 提炼成 SwiftUI 文档工作区，保留 open/save/new/select 生命周期与 mock fs 边界。',
    jsxSource: ['<DocumentGroup documents={documents} selection={selection}>', '  <TextField text={nextName} />', '  <Button title="Save" />', '</DocumentGroup>'].join('\n'),
    coverage: { aligned: ['open/save/new/select', 'document workspace facade'], stub: ['多文档并发编辑', 'autosave 策略'], gap: ['真实 NSDocument bridge'] },
  }),
  makeSpec({
    page: { id: 'component-window-group', title: 'WindowGroup', intent: '展示 window chrome、key window、open/close 生命周期 stub。', category: 'component' },
    stateModels: ['MockWindowInfo[]', 'MockSceneLifecycle'],
    apiFacades: ['SceneLifecycleProvider'],
    components: ['WindowGroup', 'Button', 'Text', 'VStack'],
    modifiers: ['frame', 'background', 'foregroundStyle'],
    fewShot: ['window chrome shell -> WindowGroup', 'open utility window -> mock lifecycle update'],
    prompt: '把 WindowGroup demo 提炼成 SwiftUI window shell reference，保留 key window 与 open/close stub 行为。',
    jsxSource: ['<WindowGroup id="preview.window" title="Preview Window">...</WindowGroup>', '<Button title="Open Utility" />'].join('\n'),
    coverage: { aligned: ['open/close window action', 'scene lifecycle'], stub: ['多窗口焦点切换'], gap: ['真实 NSWindow handle'] },
  }),
  makeSpec({
    page: { id: 'component-commands', title: 'Commands', intent: '展示 command group 注册与命令触发行为 stub。', category: 'component' },
    stateModels: ['MockCommandGroup[]', 'MockWindowInfo[]'],
    apiFacades: ['SceneLifecycleProvider', 'AppSystemApi'],
    components: ['Commands', 'Button', 'Text', 'VStack'],
    modifiers: ['padding', 'frame', 'foregroundStyle'],
    fewShot: ['file menu -> command group', 'command action -> open url / window lifecycle update'],
    prompt: '把 Commands demo 提炼成 SwiftUI command menu reference，保留 command group 注册与动作 stub。',
    jsxSource: ['<Commands id="file-menu" title="File">', '  <Button title="New Window" />', '</Commands>'].join('\n'),
    coverage: { aligned: ['command register', 'window/openUrl stub'], stub: ['phase 驱动联动'], gap: ['真实 menu bar 快捷键'] },
  }),
  makeSpec({
    page: { id: 'component-scene', title: 'Scene', intent: '展示 scene role 与 phase/lifecycle stub。', category: 'component' },
    stateModels: ['MockSceneInfo[]', 'MockSceneLifecycle'],
    apiFacades: ['SceneLifecycleProvider'],
    components: ['Scene', 'Text', 'VStack'],
    modifiers: ['padding', 'foregroundStyle'],
    fewShot: ['settings scene -> Scene(role: .settings)', 'phase display -> lifecycle stub'],
    prompt: '把 Scene demo 提炼成 SwiftUI scene reference，保留 role/phase/lifecycle stub。',
    jsxSource: ['<Scene id="settings.scene" role="settings" title="Settings Scene">', '  <Text>Scene acts as lifecycle/root grouping shell.</Text>', '</Scene>'].join('\n'),
    coverage: { aligned: ['scene role/title/id', 'phase 生命周期'], stub: ['多 scene 协调'], gap: ['真实 app scene session'] },
  }),
  makeSpec({
    page: { id: 'component-navigation-stack', title: 'NavigationStack', intent: '展示 path/value-driven 导航与本地栈状态。', category: 'component' },
    stateModels: ['NavigationPath', 'Binding<NavigationPath>'],
    apiFacades: ['SceneLifecycleProvider'],
    components: ['NavigationStack', 'NavigationLink', 'Toolbar', 'Button', 'Text'],
    modifiers: ['padding', 'frame', 'background'],
    fewShot: ['destination push -> NavigationLink(destination:)', 'value route -> NavigationLink(value:)'],
    prompt: '把 NavigationStack demo 提炼成 SwiftUI 导航 reference，保留 path/value-driven 语义与本地栈状态。',
    jsxSource: ['<NavigationStack path={path}>', '  <NavigationLink value="message-c" destination={<DetailPane />} />', '</NavigationStack>'].join('\n'),
    coverage: { aligned: ['NavigationPath', 'value push', 'route register'], stub: ['复杂 typed route'], gap: ['系统 back stack 恢复'] },
  }),
  makeSpec({
    page: { id: 'component-navigation-link', title: 'NavigationLink', intent: '展示 destination/value 双模式导航入口语义。', category: 'component' },
    stateModels: ['Binding<string>'],
    apiFacades: ['SceneLifecycleProvider'],
    components: ['NavigationLink', 'Text', 'VStack'],
    modifiers: ['padding', 'background', 'frame'],
    fewShot: ['row link -> title/value layout', 'custom label -> NavigationLink { custom label }'],
    prompt: '把 NavigationLink demo 提炼成 SwiftUI 导航入口 reference，保留 title/value、custom label、onNavigate stub。',
    jsxSource: ['<NavigationLink title="General" value="基础设置" onNavigate={...} />', '<NavigationLink value="device-detail">...</NavigationLink>'].join('\n'),
    coverage: { aligned: ['title/value', 'custom label', 'value route'], stub: ['isActive binding 兼容'], gap: ['真实 navigation destination 环境'] },
  }),
  makeSpec({
    page: { id: 'component-list', title: 'List', intent: '展示 plain/insetGrouped、selection 与 section 组合。', category: 'component' },
    stateModels: ['Binding<string | null>'],
    apiFacades: ['AppShell'],
    components: ['List', 'Section', 'NavigationLink', 'Text'],
    modifiers: ['padding', 'frame', 'background', 'labelsHidden'],
    fewShot: ['plain list -> List', 'inset grouped section list -> List + Section'],
    prompt: '把 List demo 提炼成 SwiftUI 列表 reference，保留 selection、section、style 差异。',
    jsxSource: ['<List selection={selection} style="insetGrouped">', '  <Section title="Devices">...</Section>', '</List>'].join('\n'),
    coverage: { aligned: ['selection', 'style', 'section'], stub: ['edit mode', 'swipe action'], gap: ['真实 platform list chrome'] },
  }),
  makeSpec({
    page: { id: 'component-tab-view', title: 'TabView', intent: '展示 tag/badge/disabled/tabBarHidden 页签容器语义。', category: 'component' },
    stateModels: ['Binding<string>'],
    apiFacades: ['AppShell'],
    components: ['TabView', 'Tab', 'Text', 'VStack'],
    modifiers: ['tint', 'frame', 'background'],
    fewShot: ['badge tab -> .badge(3)', 'hidden bar -> conditionally hide tab bar'],
    prompt: '把 TabView demo 提炼成 SwiftUI 页签容器 reference，保留 selection、tag、badge、disabled、tabBarHidden。',
    jsxSource: ['<TabView selection={selection} tint="green">', '  <Tab tag="contacts" title="联系人" badge={3}>...</Tab>', '</TabView>'].join('\n'),
    coverage: { aligned: ['selection/tag', 'badge', 'disabled', 'tabBarHidden'], stub: ['平台 tab style 差异'], gap: ['真实 sidebarAdaptable behavior'] },
  }),
  makeSpec({
    page: { id: 'component-sheet', title: 'Sheet', intent: '展示 detents、dismiss、modal 生命周期 stub。', category: 'component' },
    stateModels: ['Binding<boolean>'],
    apiFacades: ['SceneLifecycleProvider'],
    components: ['Sheet', 'Button', 'Text', 'HStack', 'VStack'],
    modifiers: ['padding', 'frame', 'background'],
    fewShot: ['standard sheet -> detents .large', 'compact confirm -> detents .medium + dismiss disabled'],
    prompt: '把 Sheet demo 提炼成 SwiftUI modal reference，保留 detents、dismiss 行为与内容层级。',
    jsxSource: ['<Sheet isPresented={presented} detents={["large"]}>', '  <Text>Sheet 内容</Text>', '</Sheet>'].join('\n'),
    coverage: { aligned: ['detents', 'dismiss disabled', 'title'], stub: ['平台动画'], gap: ['真实 sheet presentation controller'] },
  }),
  makeSpec({
    page: { id: 'component-popover', title: 'Popover', intent: '展示 title/arrowEdge/quick action 浮层语义。', category: 'component' },
    stateModels: ['Binding<boolean>'],
    apiFacades: ['AppSystemApi'],
    components: ['Popover', 'Button', 'Text', 'VStack'],
    modifiers: ['padding', 'frame', 'background'],
    fewShot: ['quick preview -> popover title/content', 'peer info card -> trailing edge popover'],
    prompt: '把 Popover demo 提炼成 SwiftUI quick action reference，保留 arrowEdge/title/dismiss。',
    jsxSource: ['<Popover isPresented={shown} title="Peer Info" arrowEdge="trailing">...</Popover>'].join('\n'),
    coverage: { aligned: ['title', 'arrowEdge', 'dismiss'], stub: ['anchor 定位细节'], gap: ['真实 platform adaptation'] },
  }),
  makeSpec({
    page: { id: 'component-alert', title: 'Alert', intent: '展示 primary/secondary button 与 destructive/cancel 反馈层语义。', category: 'component' },
    stateModels: ['Binding<boolean>'],
    apiFacades: ['AppSystemApi'],
    components: ['Alert', 'Button', 'Text', 'VStack'],
    modifiers: ['padding', 'foregroundStyle'],
    fewShot: ['destructive alert -> primaryButton/secondaryButton', 'feedback layer -> alert/dialog/cover split'],
    prompt: '把 Alert demo 提炼成 SwiftUI 反馈层 reference，保留 title/message、primary/secondary button、role 语义。',
    jsxSource: ['<Alert isPresented={alertPresented} title="删除会话？" primaryButton={{ title: "删除", role: "destructive" }} secondaryButton={{ title: "取消", role: "cancel" }} />'].join('\n'),
    coverage: { aligned: ['primary/secondary button', 'cancel/destructive role'], stub: ['文本本地化细节'], gap: ['真实 platform alert chrome'] },
  }),
  makeSpec({
    page: { id: 'component-confirmation-dialog', title: 'ConfirmationDialog', intent: '展示 message/titleVisibility/cancelTitle/多 action 反馈层语义。', category: 'component' },
    stateModels: ['Binding<boolean>'],
    apiFacades: ['AppSystemApi'],
    components: ['ConfirmationDialog', 'Button', 'Text', 'VStack'],
    modifiers: ['padding', 'foregroundStyle'],
    fewShot: ['multi action dialog -> actions[]', 'destructive action -> role: destructive'],
    prompt: '把 ConfirmationDialog demo 提炼成 SwiftUI 轻量动作菜单 reference，保留 message、cancelTitle、titleVisibility、actions。',
    jsxSource: ['<ConfirmationDialog isPresented={presented} title="选择操作" message="这些操作会立即影响当前会话。" actions={[{ title: "置顶" }, { title: "删除", role: "destructive" }]} />'].join('\n'),
    coverage: { aligned: ['message', 'actions', 'destructive role'], stub: ['titleVisibility 默认值'], gap: ['平台 action sheet 适配'] },
  }),
  makeSpec({
    page: { id: 'component-table', title: 'Table', intent: '展示 column/selection/rowActions 数据表语义。', category: 'component' },
    stateModels: ['Binding<string | null>'],
    apiFacades: ['AppShell'],
    components: ['Table', 'Button', 'Text', 'HStack'],
    modifiers: ['padding', 'frame', 'background'],
    fewShot: ['column config -> TableColumn[]', 'row action -> rowActions'],
    prompt: '把 Table demo 提炼成 SwiftUI 数据表 reference，保留 column、selection、rowActions 语义。',
    jsxSource: ['<Table columns={columns} dataSource={peers} selection={selection} rowActions={...} />'].join('\n'),
    coverage: { aligned: ['selection', 'rowActions', 'column layout'], stub: ['sorting'], gap: ['真实 NSTableView bridge'] },
  }),
  makeSpec({
    page: { id: 'component-picker', title: 'Picker', intent: '展示 segmented label/labelsHidden/controlSize/tint 选择器语义。', category: 'component' },
    stateModels: ['Binding<string>'],
    apiFacades: ['AppShell'],
    components: ['Picker', 'Text', 'VStack'],
    modifiers: ['tint', 'controlSize', 'labelsHidden', 'frame'],
    fewShot: ['segmented picker -> pickerStyle(.segmented)', 'label hidden -> labelsHidden()'],
    prompt: '把 Picker demo 提炼成 SwiftUI 选择器 reference，保留 segmented、label、labelsHidden、controlSize、tint。',
    jsxSource: ['<Picker selection={selection} pickerStyle="segmented" tint="green" options={[...]} />'].join('\n'),
    coverage: { aligned: ['segmented', 'labelsHidden', 'controlSize', 'tint'], stub: ['menu/wheel style'], gap: ['真实 macOS picker chrome'] },
  }),
  makeSpec({
    page: { id: 'component-toggle', title: 'Toggle', intent: '展示 title/label/tint/labelsHidden 开关语义。', category: 'component' },
    stateModels: ['Binding<boolean>'],
    apiFacades: ['AppShell'],
    components: ['Toggle', 'Text', 'VStack'],
    modifiers: ['tint', 'labelsHidden', 'frame'],
    fewShot: ['title toggle -> Toggle("Wi-Fi", isOn: $wifi)', 'custom label -> Toggle(isOn:) { custom label }'],
    prompt: '把 Toggle demo 提炼成 SwiftUI 开关 reference，保留 title/label、tint、labelsHidden 与 binding 关系。',
    jsxSource: ['<Toggle isOn={wifi} title="Wi-Fi" tint="green" />', '<Toggle isOn={notifications} label={<CustomLabel />} />'].join('\n'),
    coverage: { aligned: ['title', 'custom label', 'tint', 'labelsHidden'], stub: ['toggle style'], gap: ['真实 platform switch metrics'] },
  }),
  makeSpec({
    page: { id: 'component-slider', title: 'Slider', intent: '展示 range/step/两端 label/tint 滑杆语义。', category: 'component' },
    stateModels: ['Binding<number>'],
    apiFacades: ['AppShell'],
    components: ['Slider', 'Text', 'VStack'],
    modifiers: ['tint', 'labelsHidden', 'frame'],
    fewShot: ['bounded slider -> in + step', 'value labels -> minimumValueLabel/maximumValueLabel'],
    prompt: '把 Slider demo 提炼成 SwiftUI 滑杆 reference，保留 value/range/step、两端 label、tint。',
    jsxSource: ['<Slider value={zoom} in={[10, 200]} step={5} minimumValueLabel={<Text>10%</Text>} maximumValueLabel={<Text>200%</Text>} />'].join('\n'),
    coverage: { aligned: ['range', 'step', 'min/max label', 'tint'], stub: ['continuous update 策略'], gap: ['真实 NSSlider metrics'] },
  }),
  makeSpec({
    page: { id: 'component-stepper', title: 'Stepper', intent: '展示整数步进、label/valueLabel/controlSize 语义。', category: 'component' },
    stateModels: ['Binding<number>'],
    apiFacades: ['AppShell'],
    components: ['Stepper', 'Text', 'VStack'],
    modifiers: ['tint', 'controlSize', 'labelsHidden'],
    fewShot: ['stepper with label -> Stepper(value:in:step:label:)', 'compact config -> controlSize(.mini)'],
    prompt: '把 Stepper demo 提炼成 SwiftUI 步进器 reference，保留 range/step、label/valueLabel、controlSize。',
    jsxSource: ['<Stepper value={count} in={[0, 10]} step={1} label={<Text>Concurrent Uploads</Text>} valueLabel={<Text>{count.value}</Text>} />'].join('\n'),
    coverage: { aligned: ['range', 'step', 'label/valueLabel', 'controlSize'], stub: ['autorepeat'], gap: ['真实 NSStepper behavior'] },
  }),
  makeSpec({
    page: { id: 'component-text-field', title: 'TextField', intent: '展示 focus/submit/tint/controlSize 文本输入语义。', category: 'component' },
    stateModels: ['Binding<string>', 'FocusState<string | null>'],
    apiFacades: ['FocusedValuesProvider'],
    components: ['TextField', 'Button', 'Text', 'VStack'],
    modifiers: ['frame', 'tint', 'controlSize'],
    fewShot: ['focus binding -> focused/equals', 'submit label -> onSubmit/submitLabel'],
    prompt: '把 TextField demo 提炼成 SwiftUI 输入框 reference，保留 focus、submit、tint、controlSize。',
    jsxSource: ['<TextField text={deviceName} focused={focus} equals="deviceName" submitLabel="search" />'].join('\n'),
    coverage: { aligned: ['focus', 'submitLabel', 'tint', 'controlSize'], stub: ['formatter/axis'], gap: ['真实 NSTextField delegate'] },
  }),
  makeSpec({
    page: { id: 'component-secure-field', title: 'SecureField', intent: '展示密码输入、focus、submitLabel 安全输入语义。', category: 'component' },
    stateModels: ['Binding<string>', 'FocusState<string | null>'],
    apiFacades: ['FocusedValuesProvider'],
    components: ['SecureField', 'Button', 'Text', 'VStack'],
    modifiers: ['frame', 'controlSize'],
    fewShot: ['password binding -> SecureField(text:)', 'focus password field -> focused/equals'],
    prompt: '把 SecureField demo 提炼成 SwiftUI 安全输入框 reference，保留 text/focus/submitLabel 与 reveal-less 语义。',
    jsxSource: ['<SecureField text={password} placeholder="password" focused={focus} equals="password" submitLabel="done" />'].join('\n'),
    coverage: { aligned: ['secure text binding', 'focus', 'submitLabel'], stub: ['密码规则提示'], gap: ['原生密码自动填充'] },
  }),
  makeSpec({
    page: { id: 'component-text-editor', title: 'TextEditor', intent: '展示多行输入、focus、高度与 draft state。', category: 'component' },
    stateModels: ['Binding<string>', 'FocusState<string | null>'],
    apiFacades: ['FocusedValuesProvider'],
    components: ['TextEditor', 'Button', 'Text', 'VStack'],
    modifiers: ['frame', 'tint'],
    fewShot: ['multiline draft -> TextEditor', 'focus long editor -> focus state binding'],
    prompt: '把 TextEditor demo 提炼成 SwiftUI 多行输入 reference，保留 draft/focus/height 语义。',
    jsxSource: ['<TextEditor text={draft} focused={focus} equals="draft" frame={{ height: 140 }} />'].join('\n'),
    coverage: { aligned: ['multiline draft', 'focus', 'height'], stub: ['富文本 selection'], gap: ['原生 attributed text'] },
  }),
  makeSpec({
    page: { id: 'component-window-accessor', title: 'WindowAccessor', intent: '展示窗口句柄访问占位与 runtime/native bridge 分层边界。', category: 'component' },
    stateModels: ['MockWindowInfo[]'],
    apiFacades: ['SceneLifecycleProvider'],
    components: ['WindowAccessor', 'Text', 'VStack'],
    modifiers: ['padding', 'foregroundStyle'],
    fewShot: ['window handle placeholder -> runtime/native bridge', 'view layer 只读窗口语义，不直拿原生对象'],
    prompt: '把 WindowAccessor demo 提炼成 SwiftUI/native bridge 边界 reference，强调窗口句柄访问应下沉到 runtime。',
    jsxSource: ['<WindowAccessor>{window => <Text>{window?.id}</Text>}</WindowAccessor>'].join('\n'),
    coverage: { aligned: ['分层边界表达'], stub: ['window info 注入'], gap: ['真实 NSWindow/UIViewController handle'] },
  }),
  makeSpec({
    page: { id: 'todo', title: 'Todo List', intent: '展示输入、筛选、列表状态在小型 app 场景中的 SwiftUI 映射。', category: 'app' },
    stateModels: ['Binding<string>', 'Binding<"all" | "open" | "done">'],
    apiFacades: ['MockEnvironment'],
    components: ['Picker', 'TextField', 'Button', 'Image', 'HStack', 'VStack'],
    modifiers: ['padding', 'background', 'frame', 'foregroundStyle'],
    fewShot: ['segmented filter -> Picker', 'task row -> HStack + Image + Text'],
    prompt: '把 Todo demo 提炼成 SwiftUI 小应用 reference，保留输入、筛选、列表分组与轻量状态流。',
    jsxSource: ['<Picker selection={segment} pickerStyle="segmented" options={[...]} />', '<TextField text={input} placeholder="new task" />', '<Button title="添加" />'].join('\n'),
    coverage: { aligned: ['输入/筛选/列表状态', '小应用结构'], stub: ['新增/切换完成真实 op'], gap: ['持久化 store'] },
  }),
  makeSpec({
    page: { id: 'image-browser', title: '图片浏览器', intent: '展示网格卡片、缩略图占位、元信息布局在媒体 app 中的 SwiftUI 映射。', category: 'app' },
    stateModels: ['ImageItem[]'],
    apiFacades: ['MockEnvironment'],
    components: ['HStack', 'VStack', 'Text'],
    modifiers: ['padding', 'background', 'frame', 'foregroundStyle'],
    fewShot: ['image card grid -> HStack rows', 'thumbnail placeholder -> rounded rectangle + title'],
    prompt: '把 Image Browser demo 提炼成 SwiftUI 媒体网格 reference，保留 tile 布局、元信息、占位色块语义。',
    jsxSource: ['<HStack spacing={14}>', '  <ImageTile item={item} />', '</HStack>'].join('\n'),
    coverage: { aligned: ['tile grid', 'metadata caption'], stub: ['选中态/预览态'], gap: ['真实 image decode/cache'] },
  }),
  makeSpec({
    page: { id: 'file-browser', title: '文件浏览器', intent: '展示 sidebar + content pane 的文件浏览壳与 in-memory 文件项布局。', category: 'app' },
    stateModels: ['MockFileNode[]'],
    apiFacades: ['MockEnvironment', 'AppFileApi'],
    components: ['Button', 'Divider', 'Image', 'Spacer', 'Text', 'HStack', 'VStack'],
    modifiers: ['padding', 'background', 'frame', 'foregroundStyle'],
    fewShot: ['sidebar favorites -> VStack + buttons', 'file rows -> HStack list'],
    prompt: '把 File Browser demo 提炼成 SwiftUI 文件浏览壳 reference，保留 sidebar、toolbar、row layout 与 mock file list。',
    jsxSource: ['<HStack spacing={0}>', '  <SidebarFavorites />', '  <Divider axis="vertical" />', '  <FileRows />', '</HStack>'].join('\n'),
    coverage: { aligned: ['sidebar/content pane', 'file row layout'], stub: ['选择态/双击打开'], gap: ['真实 Finder/file provider bridge'] },
  }),
]

export const translatorPageRegistry: TranslatorPageSpec[] = specs

const translatorPageMap = new Map(specs.map(spec => [spec.page.id, spec]))

export const getTranslatorPageSpec = (pageId: string): TranslatorPageSpec | undefined => translatorPageMap.get(pageId)

export const getTranslatorPageMeta = (pageId: string): TranslatorPageMeta | undefined => getTranslatorPageSpec(pageId)?.page
